---
title: "Football Exploratory Analysis"
output:
  html_document: default
  html_notebook: default
---

```{r}
source("readDataToMemory.R")
readFootball()

library(ggplot2)
library(ggthemes)

print(dbListTables(sql_con))
```

## Pipes

```{r}
players %>%
  head

players %>%
  colnames

players %>%
  sapply(class)

class %>%
  sapply(players, .)
```



## SELECT ~ select

```{r}
players %>%
  head %>%
  select(player_name, birthday)

dbGetQuery(sql_con, "
SELECT player_name
,   birthday
FROM Player
LIMIT 6
")
```

## WHERE ~ filter

```{r}
players %>%
  filter(birthday >= "1998") %>%
  head

dbGetQuery(sql_con, "
SELECT *
FROM Player
WHERE birthday >= '1998'
LIMIT 6
")
```

## ORDER ~ arrange

```{r}
players %>%
  arrange(birthday) %>%
  head

dbGetQuery(sql_con, "
SELECT *
FROM Player
ORDER BY birthday
LIMIT 6
")
```

## aggregators ~ summarise

```{r}
players %>%
  summarise(weight=mean(weight), height=mean(height))

dbGetQuery(sql_con, "
SELECT AVG(weight) AS weight, AVG(height) AS height
FROM Player
")
```

## mutate

```{r}
players %>%
  mutate(weight_kg = weight*0.45359237) %>%
  summarise(weight=mean(weight_kg), height=mean(height))

dbGetQuery(sql_con, "
SELECT AVG(weight*0.45359237) AS weight, AVG(height) AS height
FROM Player
")

"SELECT AVG(weight*0.45359237) AS weight, AVG(height) AS height
FROM Player" %>%
  dbGetQuery(sql_con,.)
```

## GROUP BY

```{r}
players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
  group_by(year) %>%
  summarise(height=mean(height)) %>%
  ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()

"SELECT CAST(SUBSTR(birthday,1,4) AS INT) AS year, AVG(height) AS height
FROM Player
GROUP BY year" %>%
  dbGetQuery(sql_con,.) %>%
  ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```

```{r}
players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
  group_by(year) %>%
  summarise(nsample=n()) %>%
  ggplot(aes(year, nsample)) +
  geom_line(colour="darkorange") +
  theme_minimal()

"SELECT CAST(SUBSTR(birthday,1,4) AS INT) AS year, COUNT(1) AS nsample
FROM Player
GROUP BY year" %>%
  dbGetQuery(sql_con,.) %>%
  ggplot(aes(year, nsample)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```

```{r}
players %>%
  mutate(year=as.numeric(substring(birthday, 1, 4))) %>%
  group_by(year) %>%
  summarise(height=mean(height), nsamples=n()) %>%
  filter(nsamples >= 200) %>%
  ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()

"SELECT CAST(SUBSTR(birthday,1,4) AS INT) AS year, AVG(height) AS height, COUNT(1) AS nsample
FROM Player
GROUP BY year
HAVING nsample >= 200" %>%
  dbGetQuery(sql_con,.) %>%
  ggplot(aes(year, height)) +
  geom_line(colour="darkorange") +
  theme_minimal()
```

Exercise

* Translate from SQL to dply or from dply to SQL
```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Match
LIMIT 6
")

games %>%
  head(.,n=6)
```

```{r}
dbGetQuery(sql_con, "
SELECT country_id
,   COUNT(1) AS n
FROM Match
GROUP BY country_id
ORDER BY n DESC
")

games %>%
  select(country_id,id) %>%
  group_by(country_id) %>%
  summarise(n=n_distinct(id))%>%
  arrange(desc(n))
  
```

```{r}
countries

dbGetQuery(sql_con, "
SELECT *
FROM COUNTRY
")
```


```{r}
games %>%
  left_join(countries, by=c("country_id" = "id")) %>%
  select(name, home_team_api_id) %>%
  group_by(name) %>%
  summarise(teams = n_distinct(home_team_api_id)) %>%
  arrange(desc(teams))

dbGetQuery(sql_con, "
SELECT name, COUNT(1) AS teams
FROM COUNTRY c
LEFT JOIN (
    SELECT country_id
    FROM MATCH
    GROUP BY home_team_api_id
) m
ON c.id = m.country_id
GROUP BY name
ORDER BY teams DESC
")
```

```{r}
dbGetQuery(sql_con, "
SELECT *
FROM Player_Attributes
LIMIT 6
")
```

* From where do players with higest accuracy come from?

* Add team name and translate to dplyr

```{r}
dbGetQuery(sql_con, "
SELECT stage, home_team_api_id, home_team_goal
FROM Match
WHERE country_id = 1
AND season = '2008/2009'
ORDER BY stage
LIMIT 6
")

dbGetQuery(sql_con, "
SELECT m.home_team_api_id, id
FROM (
    SELECT home_team_api_id
    FROM Match
    GROUP BY home_team_api_id
) m
LEFT JOIN (
    SELECT id
    FROM Team
    GROUP BY id
) t
ON m.home_team_api_id = t.id
LIMIT 6
")
```
